import "@/styles/global.css";
import NavigationTab from "@/components/navigationTab";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <NavigationTab />
        {children}
      </body>
    </html>
  );
}
